<template>
	<div class="country">
		<div class="login">
      <img src="@/assets/img/back.png" @click="backRegister">
      选择国家和地区
  </div>
	<div>
		<mt-index-list>
			<mt-index-section :index="item.letters" v-for="(item,index) in phonedata" :key="index">
				<mt-cell :title="sitem.name" v-for="(sitem,sindex) in item.content" @click.native="selectPhone(sitem)" :key="sindex" :class="{active:selectphone==sitem.phone}" style="margin-right:0.6rem"><span>+{{sitem.phone}}</span></mt-cell>
			</mt-index-section>
		</mt-index-list>
		</div>
	</div>
</template>

<script>
	import Header from '@/common/head.vue';
		export default{
        components:{
				'v-header':Header
			},
	    data(){
	    	return{
	    		phonedata:[
                {
                  letters:'热门',content:[
                  {name:'中国',phone:'86'},
                  {name:'中国香港',phone:'852'},
                  {name:'中国澳门',phone:'853'},
                  {name:'中国台湾',phone:'886'},
                  {name:'新加坡',phone:'65'},
                  {name:'美国',phone:'1'}
                  ]
                },
           	  	{
           	  		letters:'A',content:[
	           	  	{name:'阿尔巴尼亚',phone:'355'},
	           	  	{name:'阿尔及利亚',phone:'213'},
	           	  	{name:'阿富汗',phone:'93'},
	           	  	{name:"阿根廷",phone:"54"},
	           	  	{name:"阿鲁巴岛",phone:"297"},
	           	  	{name:"阿曼",phone:"968"},
	           	  	{name:"阿塞拜疆",phone:"994"},
	           	  	{name:"阿森松(英)",phone:"247"},
	           	  	{name:"埃及",phone:"20"},
	           	  	{name:"埃塞俄比亚",phone:"251"},
	           	  	{name:"爱尔兰",phone:"353"},
	           	  	{name:"爱沙尼亚",phone:"372"},
	           	  	{name:"安道尔",phone:"376"},
	           	  	{name:"安哥拉",phone:"244"},
	           	  	{name:"安圭拉岛(英)",phone:"1264"},
	           	  	{name:"安提瓜和巴布达",phone:"1268"},
	           	  	{name:"奥地利",phone:"43"},
	           	  	{name:"澳大利亚",phone:"61"},
	           	  	{name:"澳门",phone:"853"}]
           	    },
           	    {
                    letters:'B',content:[
                    {name:"巴巴多斯",phone:"1246"},  
			        {name:"巴布亚新几内亚",phone:"675"},  
			        {name:"巴哈马国",phone:"1242"},  
			        {name:"巴基斯坦",phone:"92"},  
			        {name:"巴拉圭",phone:"595"},  
			        {name:"巴林",phone:"973"},  
			        {name:"巴拿马",phone:"507"},  
			        {name:"巴西",phone:"55"},  
			        {name:"白俄罗斯",phone:"375"},  
			        {name:"百慕大群岛(英)",phone:"1441"},  
			        {name:"保加利亚",phone:"359"},  
			        {name:"贝宁",phone:"229"},  
			        {name:"比利时",phone:"32"},  
			        {name:"冰岛",phone:"354"},  
			        {name:"波多黎各(美)",phone:"1"},  
			        {name:"波兰",phone:"48"},  
			        {name:"波斯尼亚和黑塞哥维那",phone:"387"},  
			        {name:"玻利维亚",phone:"591"},  
			        {name:"伯利兹",phone:"501"},  
			        {name:"博茨瓦纳",phone:"267"},  
			        {name:"不丹",phone:"975"},  
			        {name:"布基纳法索",phone:"226"},  
			        {name:"布隆迪",phone:"257"}
                    ]
           	    },{
           	    	letters:'C',content:[
           	    	{name:"朝鲜",phone:"850"},  
        			{name:"赤道几内亚",phone:"240"},  
        			]
           	    },{
           	    	letters:'D',content:[
           	    	{name:"丹麦",phone:"45"},  
			        {name:"德国",phone:"49"},  
			        {name:"东萨摩亚(美)",phone:"1684"},  
			        {name:"多哥",phone:"228"},  
			        {name:"多米尼加共和国",phone:"1809"},  
			        {name:"多米尼克国",phone:"1767"}  
        			]
           	    },{
           	    	letters:'E',content:[
           	    	{name:"俄罗斯",phone:"7"},  
			        {name:"厄瓜多尔",phone:"593"},  
			        {name:"厄立特里亚",phone:"291"} 
        			]
           	    },{
           	    	letters:'F',content:[
           	    	{name:"法国",phone:"33"},  
			        {name:"法罗群岛(丹)",phone:"298"},  
			        {name:"法属波里尼西亚",phone:"689"},  
			        {name:"梵蒂冈",phone:"14397"},  
			        {name:"菲律宾",phone:"63"},  
			        {name:"斐济",phone:"679"},  
			        {name:"芬兰",phone:"358"},  
			        {name:"佛得角",phone:"238"},  
			        {name:"福克兰群岛",phone:"500"}  
        			]
           	    },{
           	    	letters:'G',content:[
           	    	 {name:"冈比亚",phone:"220"},  
        {name:"刚果",phone:"242"},  
        {name:"哥伦比亚",phone:"57"},  
        {name:"哥斯达黎加",phone:"506"},  
        {name:"格林纳达",phone:"1473"},  
        {name:"格陵兰岛",phone:"299"},  
        {name:"格鲁吉亚",phone:"995"},  
        {name:"古巴",phone:"53"},  
        {name:"瓜德罗普岛(法)",phone:"590"},  
        {name:"关岛(美)",phone:"1671"},  
        {name:"圭亚那",phone:"592"}  
        			]
           	    },{
           	    	letters:'H',content:[
           	    	{name:"哈萨克斯坦",phone:"7"},  
        {name:"海地",phone:"509"},  
        {name:"韩国",phone:"82"},  
        {name:"荷兰",phone:"31"},  
        {name:"荷属安的列斯群岛",phone:"599"},  
        {name:"洪都拉斯",phone:"504"},  
        {name:"基里巴斯",phone:"686"}
        			]
           	    },{
           	    	letters:'J',content:[
           	    	{name:"吉布提",phone:"253"},
        {name:"吉尔吉斯斯坦",phone:"996"},  
        {name:"几内亚",phone:"224"},  
        {name:"几内亚比绍",phone:"245"},  
        {name:"加拿大",phone:"1"},  
        {name:"加纳",phone:"233"},  
        {name:"加蓬",phone:"241"},  
        {name:"柬埔塞",phone:"855"},  
        {name:"捷克",phone:"420"},  
        {name:"津巴布韦",phone:"263"}  
        			]
           	    },{
           	    	letters:'K',content:[
           	    	{name:"喀麦隆",phone:"237"},  
        {name:"卡塔尔",phone:"974"},  
        {name:"开曼群岛(英)",phone:"1345"},  
        {name:"科科斯岛",phone:"61"},  
        {name:"科克群岛(新)",phone:"682"},  
        {name:"科摩罗",phone:"269"},  
        {name:"科特迪瓦",phone:"225"},  
        {name:"科威特",phone:"965"},  
        {name:"克罗地亚",phone:"385"},  
        {name:"肯尼亚",phone:"254"}
        			]
           	    },{
           	    	letters:'L',content:[
           	    	{name:"拉脱维亚",phone:"371"},  
        {name:"莱索托",phone:"266"},  
        {name:"老挝",phone:"856"},  
        {name:"黎巴嫩",phone:"961"},  
        {name:"立陶宛",phone:"370"},  
        {name:"利比里亚",phone:"231"},  
        {name:"利比亚",phone:"218"},  
        {name:"列支敦士登",phone:"423"},  
        {name:"留尼汪岛",phone:"262"},  
        {name:"卢森堡",phone:"352"},  
        {name:"卢旺达",phone:"250"},  
        {name:"罗马尼亚",phone:"40"}  
        			]
           	    },{
           	    	letters:'M',content:[
           	    	{name:"马达加斯加",phone:"261"},  
        {name:"马尔代夫",phone:"960"},  
        {name:"马耳他",phone:"356"},  
        {name:"马拉维",phone:"265"},  
        {name:"马来西亚",phone:"60"},  
        {name:"马里",phone:"223"},  
        {name:"马里亚纳群岛",phone:"1670"},  
        {name:"马其顿",phone:"389"},  
        {name:"马绍尔群岛",phone:"692"},  
        {name:"马提尼克(法)",phone:"596"},  
        {name:"马约特岛",phone:"262"},  
        {name:"毛里求斯",phone:"230"},  
        {name:"毛里塔尼亚",phone:"222"},  
        {name:"美国",phone:"1"},  
        {name:"蒙古",phone:"976"},  
        {name:"蒙特塞拉特岛(英)",phone:"1664"},  
        {name:"孟加拉国",phone:"880"},  
        {name:"秘鲁",phone:"51"},  
        {name:"密克罗尼西亚(美)",phone:"691"},  
        {name:"缅甸",phone:"95"},  
        {name:"摩尔多瓦",phone:"373"},  
        {name:"摩洛哥",phone:"212"},  
        {name:"摩纳哥",phone:"377"},  
        {name:"莫桑比克",phone:"258"},  
        {name:"墨西哥",phone:"52"}  
        			]
           	    },{
           	    	letters:'N',content:[
           	    	{name:"纳米比亚",phone:"264"},  
        {name:"南非",phone:"27"},  
        {name:"南斯拉夫",phone:"381"},  
        {name:"瑙鲁",phone:"674"},  
        {name:"尼泊尔",phone:"977"},  
        {name:"尼加拉瓜",phone:"505"},  
        {name:"尼日尔",phone:"227"},  
        {name:"尼日利亚",phone:"234"},  
        {name:"纽埃岛(新)",phone:"683"},  
        {name:"挪威",phone:"47"},  
        {name:"诺福克岛(澳)",phone:"672"}  
        			]
           	    },{
           	    	letters:'P',content:[
           	    	{name:"帕劳(美)",phone:"680"},  
        {name:"葡萄牙",phone:"351"}
        			]
           	    },{
           	    	letters:'R',content:[
           	    	{name:"日本",phone:"81"},  
        {name:"瑞典",phone:"46"},  
        {name:"瑞士",phone:"41"}
        			]
           	    },{
           	    	letters:'S',content:[
           	    	{name:"萨尔瓦多",phone:"503"},  
        {name:"塞拉利昂",phone:"232"},  
        {name:"塞内加尔",phone:"221"},  
        {name:"塞浦路斯",phone:"357"},  
        {name:"塞舌尔",phone:"248"},  
        {name:"桑给巴尔",phone:"259"},  
        {name:"沙特阿拉伯",phone:"966"},  
        {name:"圣诞岛",phone:"61"},  
        {name:"圣多美和普林西比",phone:"239"},  
        {name:"圣赫勒拿",phone:"290"},  
        {name:"圣克里斯托弗和尼维斯",phone:"1869"},  
        {name:"圣卢西亚",phone:"1758"},  
        {name:"圣马力诺",phone:"378"},  
        {name:"圣皮埃尔岛及密克隆岛",phone:"508"},  
        {name:"圣文森特岛(英)",phone:"1784"},  
        {name:"斯里兰卡",phone:"94"},  
        {name:"斯洛伐克",phone:"421"},  
        {name:"斯洛文尼亚",phone:"386"},  
        {name:"斯威士兰",phone:"268"},  
        {name:"苏丹",phone:"249"},  
        {name:"苏里南",phone:"597"},  
        {name:"所罗门群岛",phone:"677"},  
        {name:"索马里",phone:"252"}
        			]
           	    },
           	    {
           	    	letters:'T',content:[
           	    	{name:"塔吉克斯坦",phone:"992"},  
        {name:"台湾",phone:"886"},  
        {name:"泰国",phone:"66"},  
        {name:"坦桑尼亚",phone:"255"},  
        {name:"汤加",phone:"676"},  
        {name:"特克斯和凯科斯群岛(英)",phone:"1649"},  
        {name:"特立尼达和多巴哥",phone:"1868"},  
        {name:"突尼斯",phone:"216"},  
        {name:"图瓦卢",phone:"688"},  
        {name:"土耳其",phone:"90"},  
        {name:"土库曼斯坦",phone:"993"}  
        			]
           	    },{
           	    	letters:'W',content:[
           	    	{name:"瓦努阿图",phone:"678"},  
        {name:"危地马拉",phone:"502"},  
        {name:"维尔京群岛(英)",phone:"1340"},  
        {name:"委内瑞拉",phone:"58"},  
        {name:"乌干达",phone:"256"},  
        {name:"乌克兰",phone:"380"},  
        {name:"乌拉圭",phone:"598"},  
        {name:"乌兹别克斯坦",phone:"998"}  
        			]
           	    },{
           	    	letters:'X',content:[
           	    	{name:"西班牙",phone:"34"},  
        {name:"西萨摩亚",phone:"685"},  
        {name:"希腊",phone:"30"},  
        {name:"香港",phone:"852"},  
        {name:"新加坡",phone:"65"},  
        {name:"新喀里多尼亚群岛(法)",phone:"687"},  
        {name:"新西兰",phone:"64"},  
        {name:"匈牙利",phone:"36"},  
        {name:"叙利亚",phone:"963"} 
        			]
           	    },{
           	    	letters:'Y',content:[
           	    	{name:"牙买加",phone:"1876"},  
        {name:"亚美尼亚",phone:"374"},  
        {name:"也门",phone:"967"},  
        {name:"伊拉克",phone:"964"},  
        {name:"伊郎",phone:"98"},  
        {name:"以色列",phone:"972"},  
        {name:"意大利",phone:"39"},  
        {name:"印度",phone:"91"},  
        {name:"印度尼西亚",phone:"62"},  
        {name:"英国",phone:"44"},  
        {name:"约旦",phone:"962"},  
        {name:"越南",phone:"84"} 
        			]
           	    },{
           	    	letters:'Z',content:[
           	    	{name:"赞比亚",phone:"260"},  
        {name:"乍得",phone:"235"},  
        {name:"直布罗陀(英)",phone:"350"},  
        {name:"智利",phone:"56"},  
        {name:"中非",phone:"236"},  
        {name:"中国大陆",phone:"86"}  
        			]
           	    },
           	  ],
           	  selectphone:'86'
	    	}
	    },
	    methods:{
	    	selectPhone(i){
          console.log(1)
             this.selectphone = i.phone
             console.log(this.selectphone)
         },
        backRegister(){
             console.log(1)
             this.$emit('selectPhone',this.selectphone)
        },
	    }
		}
</script>

<style lang="less" scoped>
	.country{
		font-size: 0.3rem;
	}
	.active{
			background: #ccc;
		}
  .login{
    width: 100vw;
    background-color: rgb(246,248,250);
    height: 8vh;
    line-height: 8vh;
    text-align: center;
    /*position: absolute;
    top: 0;*/
    font-size: 0.3rem;
    border-bottom: 0.02rem solid #CCC;
    img{
    margin-left: 3vw;
    margin-top: 2vh;
    height: 4vh;
    width: 8vw;
    float: left;
  }
  }
</style>